spring:
  profiles:
    active: prod
    datasource:
      dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      jpa:
        database-platform: org.hibernate.dialect.PostgreSQL82Dialect
        database: POSTGRESQL